// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.ybh.dfs.namenode.rpc.model;

public interface GetDataNodeForFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ybh.dfs.namenode.rpc.GetDataNodeForFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string filename = 1;</code>
   */
  String getFilename();
  /**
   * <code>optional string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
