// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.ybh.dfs.namenode.rpc.model;

public interface GetDataNodeForFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ybh.dfs.namenode.rpc.GetDataNodeForFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string datanodeInfo = 1;</code>
   */
  String getDatanodeInfo();
  /**
   * <code>optional string datanodeInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatanodeInfoBytes();
}
