// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.ybh.dfs.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_CreateFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_RebalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_RebalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ybh_dfs_namenode_rpc_RebalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ybh_dfs_namenode_rpc_RebalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022\030com.ybh.dfs.na" +
      "menode.rpc\"@\n\017RegisterRequest\022\n\n\002ip\030\001 \001(" +
      "\t\022\020\n\010hostname\030\002 \001(\t\022\017\n\007nioPort\030\003 \001(\005\"\"\n\020" +
      "RegisterResponse\022\016\n\006status\030\001 \001(\005\"A\n\020Hear" +
      "tbeatRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001" +
      "(\t\022\017\n\007nioPort\030\003 \001(\005\"5\n\021HeartbeatResponse" +
      "\022\016\n\006status\030\001 \001(\005\022\020\n\010commands\030\002 \001(\t\"\034\n\014Mk" +
      "dirRequest\022\014\n\004path\030\001 \001(\t\"\037\n\rMkdirRespons" +
      "e\022\016\n\006status\030\001 \001(\005\"\037\n\017ShutdownRequest\022\014\n\004" +
      "code\030\001 \001(\005\"\"\n\020ShutdownResponse\022\016\n\006status",
      "\030\001 \001(\005\"*\n\024FetchEditsLogRequest\022\022\n\nsynced" +
      "Txid\030\001 \001(\003\")\n\025FetchEditsLogResponse\022\020\n\010e" +
      "ditsLog\030\001 \001(\t\"+\n\033UpdateCheckpointTxidReq" +
      "uest\022\014\n\004txid\030\001 \001(\003\".\n\034UpdateCheckpointTx" +
      "idResponse\022\016\n\006status\030\001 \001(\005\"%\n\021CreateFile" +
      "Request\022\020\n\010filename\030\001 \001(\t\"$\n\022CreateFileR" +
      "esponse\022\016\n\006status\030\001 \001(\005\">\n\030AllocateDataN" +
      "odesRequest\022\020\n\010filename\030\001 \001(\t\022\020\n\010fileSiz" +
      "e\030\002 \001(\003\".\n\031AllocateDataNodesResponse\022\021\n\t" +
      "datanodes\030\001 \001(\t\"N\n\034InformReplicaReceived",
      "Request\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\020\n" +
      "\010filename\030\003 \001(\t\"/\n\035InformReplicaReceived" +
      "Response\022\016\n\006status\030\001 \001(\005\"k\n ReportComple" +
      "teStorageInfoRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010host" +
      "name\030\002 \001(\t\022\021\n\tfilenames\030\003 \001(\t\022\026\n\016storedD" +
      "ataSize\030\004 \001(\003\"3\n!ReportCompleteStorageIn" +
      "foResponse\022\016\n\006status\030\001 \001(\005\"P\n!ChooseData" +
      "NodeFromReplicasRequest\022\020\n\010filename\030\001 \001(" +
      "\t\022\031\n\021excludeDataNodeId\030\002 \001(\t\"6\n\"ChooseDa" +
      "taNodeFromReplicasResponse\022\020\n\010datanode\030\001",
      " \001(\t\"Z\n\031ReallocateDataNodeRequest\022\020\n\010fil" +
      "ename\030\001 \001(\t\022\020\n\010filesize\030\002 \001(\003\022\031\n\021exclude" +
      "DataNodeId\030\003 \001(\t\".\n\032ReallocateDataNodeRe" +
      "sponse\022\020\n\010datanode\030\001 \001(\t\"\022\n\020RebalanceReq" +
      "uest\"#\n\021RebalanceResponse\022\016\n\006status\030\001 \001(" +
      "\005B4\n\036com.ybh.dfs.namenode.rpc.modelB\020Nam" +
      "eNodeRpcModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ybh_dfs_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ybh_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_RegisterRequest_descriptor,
        new String[] { "Ip", "Hostname", "NioPort", });
    internal_static_com_ybh_dfs_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ybh_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_RegisterResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_ybh_dfs_namenode_rpc_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ybh_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_HeartbeatRequest_descriptor,
        new String[] { "Ip", "Hostname", "NioPort", });
    internal_static_com_ybh_dfs_namenode_rpc_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ybh_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_HeartbeatResponse_descriptor,
        new String[] { "Status", "Commands", });
    internal_static_com_ybh_dfs_namenode_rpc_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ybh_dfs_namenode_rpc_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_MkdirRequest_descriptor,
        new String[] { "Path", });
    internal_static_com_ybh_dfs_namenode_rpc_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ybh_dfs_namenode_rpc_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_MkdirResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_ybh_dfs_namenode_rpc_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_ybh_dfs_namenode_rpc_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ShutdownRequest_descriptor,
        new String[] { "Code", });
    internal_static_com_ybh_dfs_namenode_rpc_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_ybh_dfs_namenode_rpc_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ShutdownResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogRequest_descriptor,
        new String[] { "SyncedTxid", });
    internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_FetchEditsLogResponse_descriptor,
        new String[] { "EditsLog", });
    internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidRequest_descriptor,
        new String[] { "Txid", });
    internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_UpdateCheckpointTxidResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_ybh_dfs_namenode_rpc_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_ybh_dfs_namenode_rpc_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_CreateFileRequest_descriptor,
        new String[] { "Filename", });
    internal_static_com_ybh_dfs_namenode_rpc_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_ybh_dfs_namenode_rpc_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_CreateFileResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesRequest_descriptor,
        new String[] { "Filename", "FileSize", });
    internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_AllocateDataNodesResponse_descriptor,
        new String[] { "Datanodes", });
    internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedRequest_descriptor,
        new String[] { "Ip", "Hostname", "Filename", });
    internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_InformReplicaReceivedResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoRequest_descriptor,
        new String[] { "Ip", "Hostname", "Filenames", "StoredDataSize", });
    internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ReportCompleteStorageInfoResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor,
        new String[] { "Filename", "ExcludeDataNodeId", });
    internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor,
        new String[] { "Datanode", });
    internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeRequest_descriptor,
        new String[] { "Filename", "Filesize", "ExcludeDataNodeId", });
    internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_ReallocateDataNodeResponse_descriptor,
        new String[] { "Datanode", });
    internal_static_com_ybh_dfs_namenode_rpc_RebalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_ybh_dfs_namenode_rpc_RebalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_RebalanceRequest_descriptor,
        new String[] { });
    internal_static_com_ybh_dfs_namenode_rpc_RebalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_ybh_dfs_namenode_rpc_RebalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ybh_dfs_namenode_rpc_RebalanceResponse_descriptor,
        new String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
